### ISSUE TITLE
karma tests fail

### ISSUE THREAD

**Issue by noffle** [ipfs/js-ipfs-data-importing#10]
[Current `master`](https://github.com/ipfs/js-ipfs-data-importing/commit/9abcdeba0a53f609a40eec99de9c133a8ae69e0f) fails karma tests consistently for me.

```
> ipfs-data-importing@0.3.0 test:browser /home/stephen/Projects/Forks/js-ipfs-data-importing
> karma start karma.conf.js

21 03 2016 14:50:46.822:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
21 03 2016 14:50:46.837:INFO [launcher]: Starting browser Chrome
21 03 2016 14:50:48.082:INFO [Chrome 47.0.2526 (Linux 0.0.0)]: Connected on socket /#yxy1MXqYlTtHP8MdAAAA with id 20921352
21 03 2016 14:50:53.437:WARN [Chrome 47.0.2526 (Linux 0.0.0)]: Disconnected (1 times)

Chrome 47.0.2526 (Linux 0.0.0): Executed 0 of 5 DISCONNECTED (4.58 secs / 0 secs)
```

---

cc @nginnever

**Comment by nginnever** [comment]
```npm run test:browser``` runs the karma conf with all of our webpack madness. I'm not sure running the karma conf directly will work. 

cc @dignifiedquire

**Comment by noffle** [comment]
`npm test` executes `test:browser`, making local tests fail for me. :(

**Comment by nginnever** [comment]
Sorry i didn't see that, edited my comment above.

```npm run test:browser``` works for me

Are there any errors thrown or does it simply not test like above?

Travis seems to be failing on time out on your PR
https://github.com/nginnever/js-ipfs-data-importing/blob/master/tests/buffer-test.js#L26

**Comment by noffle** [comment]
No errors output other than what I posted above.

I don't think my PR is related, since Karma tests fail even on the 0.3.0 release commit when I run them. I haven't had this problem on any other repos that have Karma tests.

**Comment by noffle** [comment]
Fails on Firefox 45 too:

```
> ipfs-data-importing@0.3.0 test:browser /home/stephen/Projects/Forks/js-ipfs-data-importing
> karma start karma.conf.js

21 03 2016 15:27:50.220:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
21 03 2016 15:27:50.234:INFO [launcher]: Starting browser Firefox
21 03 2016 15:27:51.909:INFO [Firefox 45.0.0 (Linux 0.0.0)]: Connected on socket /#qfk8zRm-4EHeX3RTAAAA with id 80250265
21 03 2016 15:27:56.820:ERROR [launcher]: Firefox crashed.
	
21 03 2016 15:27:56.851:INFO [launcher]: Trying to start Firefox again (1/2).
21 03 2016 15:27:58.781:WARN [Firefox 45.0.0 (Linux 0.0.0)]: Disconnected (1 times)

Firefox 45.0.0 (Linux 0.0.0): Executed 0 of 5 DISCONNECTED (6.26 secs / 0 secs)
```

**Comment by noffle** [comment]
Upgraded to Chromium 49 -- no change in the error experienced.

**Comment by nginnever** [comment]
Can you try running the tests on js-ipfs-merkle-dag module? They are structured in exactly the same way but those tests don't have a 1.2Mb file to be buffered.

**Comment by noffle** [comment]
Yes, the js-ipfs-merkle-dag tests have work fine for me.

**Comment by diasdavid** [comment]
Travis is failing on https://github.com/ipfs/js-ipfs-data-importing/commit/463454d45ee91b87702397f88abead76289142fe yet it is not part of the history anymore. @noffle ?

Tests run fine for me on Chrome, but not on Firefox on travis(anymore) https://github.com/ipfs/js-ipfs-data-importing/pull/11 . They were fine yesterday https://travis-ci.org/ipfs/js-ipfs-data-importing/builds/117366855 . @nginnever thoughts?

**Comment by diasdavid** [comment]
greeeen :) https://github.com/ipfs/js-ipfs-data-importing/pull/12

**Comment by noffle** [comment]
Fixed in https://github.com/ipfs/js-ipfs-data-importing/pull/8. The home-made chunker used was allocating ~O(100n) bytes, causing the 1.2mb file to crash Chrome and Firefox. I switched us to block-stream2, which is O(n) and supports zero-padding too.
