### ISSUE TITLE
Files Metadata

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs-data-importing#3]
@whyrusleeping can you detail what is the meta data that the files API adds to the MerkleDAG nodes? Where do things like "Type: File" (https://github.com/ipfs/js-ipfs-api/blob/feat/files-api/test/api/files.spec.js#L43) get added?

**Comment by whyrusleeping** [comment]
we encode that information in the unixfs protobuf and store it in the data segment of the merkledag node: https://github.com/ipfs/go-ipfs/blob/master/unixfs/format.go

**Comment by diasdavid** [comment]
Where is this `metadata` schema used throughout the files api routines https://github.com/ipfs/go-ipfs/blob/master/unixfs/format.go#L17?

**Comment by diasdavid** [comment]
One more question. When we have a directory, we use the Links file on the MerkleDAG.proto to point to the files and not the data field on the unixFS proto, right?

**Comment by diasdavid** [comment]
Another one: Why do symlinks have on their data field the name of the file they are symlinking (just that) and why is that name appended by `\u0018\b`?
